# Generated by Django 6.1.1 on 2026-09-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('imagen_large', models.URLField()),
                ('imagen_medium', models.URLField()),
                ('imagen_thumbnail', models.URLField()),
                ('fecha_registro', models.CharField(max_length=50)),
            ],
        ),
    ]
