# Generated by Django 6.1.1 on 2026-09-29 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='uuid',
            new_name='id',
        ),
    ]
